name: Build Pusaka Rinjani Windows

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Application
    runs-on: windows-latest
    env:
      CL: "/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Pusaka Rinjani Windows
        uses: actions/upload-artifact@v4
        with:
          name: Pusaka-Rinjani-Windows
          path: build/windows/x64/runner/Release