name: Build Pusaka Rinjani macOS

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS Application
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos --release

      - name: Check build output
        run: ls -lah build/macos/Build/Products/Release

      - name: Create ZIP
        run: |
          cd build/macos/Build/Products/Release
          zip -r Pusaka-Rinjani-macOS-Intel.zip *.app

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: Pusaka-Rinjani-macOS
          path: build/macos/Build/Products/Release/Pusaka-Rinjani-macOS.zip